### ISSUE TITLE
数据下载不能使用

### ISSUE THREAD

**Issue by jshen28** [hansu1017/PAKDD2021-#2]
您好，数据下载的链接现在不能使用了。。请问您现在还有数据的备份能分享一下吗？谢谢。

**Comment by hansu1017** [comment]
可以的，方便留一个邮箱吗，我邮件发给您。

**Comment by jshen28** [comment]
谢谢，麻烦发到315290455@qq.com把，谢谢！

**Comment by jshen28** [comment]
您好，数据已经收到了，谢谢！另外还有一个问题想请教一下。。请问`故障文本模板`是什么意思呢？

**Comment by hansu1017** [comment]
故障模板是表示某故障是否出现变量，该变量为布尔值，其中True表示该故障文本模板出现在内核日志中，至于具体是什么故障题目中没有给出。以上是我的理解，希望对您能有所帮助~

**Comment by jshen28** [comment]
好的，谢谢！

**Comment by scwu1008** [comment]
> 可以的，方便留一个邮箱吗，我邮件发给您。

请问您那边还有数据吗？
